### ISSUE TITLE
hello I have some questions:

### ISSUE THREAD

**Issue by r3k2** [NoobieDog/maltegolocal#1]
Was looking at the python api and it has some getVar and things like that but not sure if this is what I need for:
- how I I enter another input? lets say I need the domain but I manually want to enter the ports to scan?
- how do I get values from other results chain up? as in domain--->IP--port--- now I write a transfrom that I need the result from IP and PORT to pass to my go code..

now sure if there is any other go lib for maltego but if you know of anyone that is updated please let me know.

**Comment by sroberts** [comment]
@ChrisFernandez These questions are hard to help with as abstract concepts. Can you share some code to help illustrate your questions?

**Comment by NoobieDog** [comment]
sorry guys, i will get back to these questions later in the week as im away
at the moment.

Thanks for the patients

Stu

**Comment by r3k2** [comment]
Hello @sroberts there is a better explanation here: https://github.com/glennzw/maltegogo/issues/1

**Comment by r3k2** [comment]
@NoobieDog coming back to start developing some pentest tools for maltego.. is this project still alive? I seen no updates at all not even to my question. thanks

**Comment by NoobieDog** [comment]
@glennzw has Go code too for maltego, 

I havent done any more dev on this but it still works as intended. 

i didnt code in a getvar like in the python modual but it shouldnt be too hard to add. 

Stu
